/**
 *
 *  Users.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/BaseBuilder.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/SqlBinder.h>
#ifdef __cpp_impl_coroutine
    #include <drogon/orm/CoroMapper.h>
#endif
#include <iostream>
#include <memory>
#include <string>
#include <string_view>
#include <tuple>
#include <vector>

#include <json/json.h>
#include <stdint.h>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>

namespace drogon {
    namespace orm {
        class DbClient;
        using DbClientPtr = std::shared_ptr<DbClient>;
    } // namespace orm
} // namespace drogon

namespace drogon_model {
    namespace demo {

        class Users {
        public:
            struct Cols {
                static const std::string _id;
                static const std::string _name;
                static const std::string _email;
                static const std::string _created_at;
                static const std::string _updated_at;
            };

            static const int primaryKeyNumber;
            static const std::string tableName;
            static const bool hasPrimaryKey;
            static const std::string primaryKeyName;
            using PrimaryKeyType = int64_t;
            const PrimaryKeyType& getPrimaryKey() const;

            /**
             * @brief constructor
             * @param r One row of records in the SQL query result.
             * @param indexOffset Set the offset to -1 to access all columns by column names,
             * otherwise access all columns by offsets.
             * @note If the SQL is not a style of 'select * from table_name ...' (select all
             * columns by an asterisk), please set the offset to -1.
             */
            explicit Users(const drogon::orm::Row& r, const ssize_t indexOffset = 0) noexcept;

            /**
             * @brief constructor
             * @param pJson The json object to construct a new instance.
             */
            explicit Users(const Json::Value& pJson) noexcept(false);

            /**
             * @brief constructor
             * @param pJson The json object to construct a new instance.
             * @param pMasqueradingVector The aliases of table columns.
             */
            Users(const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false);

            Users() = default;

            void updateByJson(const Json::Value& pJson) noexcept(false);
            void updateByMasqueradedJson(const Json::Value& pJson,
                                         const std::vector<std::string>& pMasqueradingVector) noexcept(false);
            static bool validateJsonForCreation(const Json::Value& pJson, std::string& err);
            static bool validateMasqueradedJsonForCreation(const Json::Value&,
                                                           const std::vector<std::string>& pMasqueradingVector,
                                                           std::string& err);
            static bool validateJsonForUpdate(const Json::Value& pJson, std::string& err);
            static bool validateMasqueradedJsonForUpdate(const Json::Value&,
                                                         const std::vector<std::string>& pMasqueradingVector,
                                                         std::string& err);
            static bool validJsonOfField(size_t index,
                                         const std::string& fieldName,
                                         const Json::Value& pJson,
                                         std::string& err,
                                         bool isForCreation);

            /**  For column id  */
            /// Get the value of the column id, returns the default value if the column is null
            const int64_t& getValueOfId() const noexcept;
            /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<int64_t>& getId() const noexcept;
            /// Set the value of the column id
            void setId(const int64_t& pId) noexcept;

            /**  For column name  */
            /// Get the value of the column name, returns the default value if the column is null
            const std::string& getValueOfName() const noexcept;
            /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<std::string>& getName() const noexcept;
            /// Set the value of the column name
            void setName(const std::string& pName) noexcept;
            void setName(std::string&& pName) noexcept;

            /**  For column email  */
            /// Get the value of the column email, returns the default value if the column is null
            const std::string& getValueOfEmail() const noexcept;
            /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<std::string>& getEmail() const noexcept;
            /// Set the value of the column email
            void setEmail(const std::string& pEmail) noexcept;
            void setEmail(std::string&& pEmail) noexcept;

            /**  For column created_at  */
            /// Get the value of the column created_at, returns the default value if the column is null
            const ::trantor::Date& getValueOfCreatedAt() const noexcept;
            /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<::trantor::Date>& getCreatedAt() const noexcept;
            /// Set the value of the column created_at
            void setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept;

            /**  For column updated_at  */
            /// Get the value of the column updated_at, returns the default value if the column is null
            const ::trantor::Date& getValueOfUpdatedAt() const noexcept;
            /// Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<::trantor::Date>& getUpdatedAt() const noexcept;
            /// Set the value of the column updated_at
            void setUpdatedAt(const ::trantor::Date& pUpdatedAt) noexcept;

            static size_t getColumnNumber() noexcept { return 5; }

            static const std::string& getColumnName(size_t index) noexcept(false);

            Json::Value toJson() const;
            Json::Value toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector) const;
            /// Relationship interfaces

        private:
            friend drogon::orm::Mapper<Users>;
            friend drogon::orm::BaseBuilder<Users, true, true>;
            friend drogon::orm::BaseBuilder<Users, true, false>;
            friend drogon::orm::BaseBuilder<Users, false, true>;
            friend drogon::orm::BaseBuilder<Users, false, false>;
#ifdef __cpp_impl_coroutine
            friend drogon::orm::CoroMapper<Users>;
#endif
            static const std::vector<std::string>& insertColumns() noexcept;
            void outputArgs(drogon::orm::internal::SqlBinder& binder) const;
            const std::vector<std::string> updateColumns() const;
            void updateArgs(drogon::orm::internal::SqlBinder& binder) const;
            /// For mysql or sqlite3
            void updateId(const uint64_t id);
            std::shared_ptr<int64_t> id_;
            std::shared_ptr<std::string> name_;
            std::shared_ptr<std::string> email_;
            std::shared_ptr<::trantor::Date> createdAt_;
            std::shared_ptr<::trantor::Date> updatedAt_;

            struct MetaData {
                const std::string colName_;
                const std::string colType_;
                const std::string colDatabaseType_;
                const ssize_t colLength_;
                const bool isAutoVal_;
                const bool isPrimaryKey_;
                const bool notNull_;
            };

            static const std::vector<MetaData> metaData_;
            bool dirtyFlag_[5] = { false };

        public:
            static const std::string& sqlForFindingByPrimaryKey() {
                static const std::string sql = "select * from " + tableName + " where id = $1";
                return sql;
            }

            static const std::string& sqlForDeletingByPrimaryKey() {
                static const std::string sql = "delete from " + tableName + " where id = $1";
                return sql;
            }

            std::string sqlForInserting(bool& needSelection) const {
                std::string sql = "insert into " + tableName + " (";
                size_t parametersCount = 0;
                needSelection = false;
                sql += "id,";
                ++parametersCount;
                if (dirtyFlag_[1]) {
                    sql += "name,";
                    ++parametersCount;
                }
                if (dirtyFlag_[2]) {
                    sql += "email,";
                    ++parametersCount;
                }
                sql += "created_at,";
                ++parametersCount;
                if (!dirtyFlag_[3]) {
                    needSelection = true;
                }
                sql += "updated_at,";
                ++parametersCount;
                if (!dirtyFlag_[4]) {
                    needSelection = true;
                }
                needSelection = true;
                if (parametersCount > 0) {
                    sql[sql.length() - 1] = ')';
                    sql += " values (";
                } else {
                    sql += ") values (";
                }

                int placeholder = 1;
                char placeholderStr[64];
                size_t n = 0;
                sql += "default,";
                if (dirtyFlag_[1]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                }
                if (dirtyFlag_[2]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                }
                if (dirtyFlag_[3]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                } else {
                    sql += "default,";
                }
                if (dirtyFlag_[4]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                } else {
                    sql += "default,";
                }
                if (parametersCount > 0) {
                    sql.resize(sql.length() - 1);
                }
                if (needSelection) {
                    sql.append(") returning *");
                } else {
                    sql.append(1, ')');
                }
                LOG_TRACE << sql;
                return sql;
            }
        };
    } // namespace demo
} // namespace drogon_model
